avatar: "images/yosimte-sam.png"
favicon_ico: "images/yosimte-sam.png"
logo:  "images/yosimte-sam.png"
nav_enabled: true
layout: default
# title: "Hacking the web"
description: "Personal notes for linux,coding,web."
title_image: "images/yosimte-sam.png"
minima:
  skin: dark
theme_mode: dark
color_scheme: dark
remote_theme: jekyll/minima
plugins:
- jekyll-remote-theme
name: TxHammer - DigiTech
author: TxHammer
description: Hacking the Web
url: https://github.com/txhammer68
#baseurl: ./
markdown: kramdown
input: GFM
github: https://github.com/txhammer68
github_username: txhammer68
reddit_username: txhammer68
repository: txhammer68
