# remote_theme: pages-themes/midnight@v0.2.0
remote_theme: andrewbanchich/forty-jekyll-theme
# theme: jekyll-theme-minimal
# remote_theme: chrisrhymes/bulma-clean-theme
# theme: txhammer68/forty
# theme: txhammer68/myweb
# https://pages.github.com/themes/
#  https://drjekyllthemes.github.io/
logo: images/yosimte-sam3.png
name: TxHammer - DigiTech
author: TxHammer
title: TxHammer
description:    Hacking the Web
url: https://github.com/txhammer68
#baseurl: ./
markdown: kramdown
input: GFM
github: https://github.com/txhammer68
github_username: txhammer68
repository: txhammer68
paypal: "https://www.paypal.com/paypalme/taylorcm68"
