theme_mode: dark
avatar: "images/yosimte-sam.png"
# title: "Hacking the web"
description: "Personal notes for linux,coding,web."
title_image: "images/yosimte-sam.png"
# theme: pages-themes/primer@v0.2.0
remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme
# remote_theme: jekyll/minima
# tactile:
 # skin: dark
  # avatar: images/yosimte-sam.png
# remote_theme: chrisrhymes/bulma-clean-theme
# theme: txhammer68/forty
# theme: txhammer68/myweb
# https://github.com/topics/jekyll-theme
# https://pages.github.com/themes/
#  https://drjekyllthemes.github.io/
logo: images/yosimte-sam.png
name: TxHammer - DigiTech
author: TxHammer
description: Hacking the Web
url: https://github.com/txhammer68
#baseurl: ./
markdown: kramdown
input: GFM
github: https://github.com/txhammer68
github_username: txhammer68
reddit_username: txhammer68
repository: txhammer68
