theme: jekyll-theme-minimal
logo: images/ai_64.png
name: TxHammer - DigiTech
author: TxHammer
title: Projects
description: Developing Web,JS,QML Skills
url: https://github.com/txhammer68
baseurl: "/docs"
markdown: kramdown
input: GFM
github: https://github.com/txhammer68
