# theme: jekyll-theme-minimal
# theme: txhammer68/chalk
remote_theme: txhammer68/minimal-mistakes
logo: images/ai_64.png
name: TxHammer - DigiTech
author: TxHammer
title: Projects
description: Developing Web,JS,QML Skills
url: https://github.com/txhammer68
baseurl: "../"
markdown: kramdown
input: GFM
github: https://github.com/txhammer68
github_username: txhammer68
plugins: jekyll-remote-theme, jekyll-include-cache
# remote_theme: txhammer68/chalk

theme: jekyll-theme-slate