theme: jekyll-theme-minimal
logo: images/ai_64.png
name: TxHammer - DigiTech
title: Projects
description: Developing Web,JS,QML Skills
url: https://github.com/txhammer68
# baseurl: ""
markdown: kramdown
