# remote_theme: mmistakes/jekyll-theme-basically-basic
titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true
# remote_theme:   cotes2020/jekyll-theme-chirpy
theme_mode: dark
avatar: 'images/yosimte-sam.png'
title: "Hacking the web"
description: "Personal notes for linux,coding,web."
title_image: "images/yosimte-sam.png"
# blog_theme: dark # Or use dark
theme: chirpy
# remote_theme: jekyll/minima
#minima:
 # skin: dark
  # avatar: images/yosimte-sam.png
# remote_theme: chrisrhymes/bulma-clean-theme
# theme: txhammer68/forty
# theme: txhammer68/myweb
# https://github.com/topics/jekyll-theme
# https://pages.github.com/themes/
#  https://drjekyllthemes.github.io/
logo: images/yosimte-sam.png
name: TxHammer - DigiTech
author: TxHammer
description: Hacking the Web
url: https://github.com/txhammer68
#baseurl: ./
markdown: kramdown
input: GFM
github: https://github.com/txhammer68
github_username: txhammer68
reddit_username: txhammer68
repository: txhammer68
paypal: "https://www.paypal.com/paypalme/taylorcm68"
