theme: jekyll-theme-minimal
# remote_theme: chrisrhymes/bulma-clean-theme
# theme: txhammer68/chalk
# theme: txhammer68/myweb
logo: images/yosimte-sam3.png
name: TxHammer - DigiTech
author: TxHammer
title: TxHammer
description: Hacking the Web,JS,QML
url: https://github.com/txhammer68
# baseurl: ./
markdown: kramdown
input: GFM
github: https://github.com/txhammer68
github_username: txhammer68
repository: txhammer68
navbar-links:
paypal:"https://www.paypal.com/paypalme/taylorcm68"
